#!/usr/bin/env python

# Python Scripting by Cornbread
# In The Begining

# Import various librarys
#import CHIP_IO.GPIO as GPIO
import time
import random
import pyperclip

# Global Variables
author = 'Cornbread'

# Defines
def cb():
	clipboard = pyperclip.paste()
	return clipboard

def lotto(min, max):
	number = random.randint(min, max)
	return number

# Introduction
print('Hello Cruel World!')
time.sleep( 1 )

# Gather the current time
time_now = time.localtime()
hour = time_now.tm_hour
minute = time_now.tm_min

if hour > 12:
    hour = hour - 12
    shift = 'PM'
elif hour < 13:
    shift = 'AM'

if minute < 10:
    tens = 0
elif minute > 9:
    tens = ''

print('The current time is', end=" ")
print(hour, end="")
print(':', tens, minute, sep="", end=" ")
print(shift)
time.sleep( 1 )

# Gather name
name = input('What is your name?\n')
print('Hello', name)
time.sleep( 1 )

# Grab a lucky number
number = lotto(100, 999)
print('Your lucky number is', number)
if number == 420:
    print('Wow! Thats a great number.')

time.sleep( 2 )

print('This scripts was written by:', author)
